version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "2181:2181"
    env_file:
      - kafka.env
    networks:
      - network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9999:9999"
    env_file:
      - kafka.env
    networks:
      - network
      - monitoring

  postgres:
    image: 'postgres:15'
    container_name: 'bench_db'
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@postgres:5432/bench-db?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring
    depends_on:
      - postgres

  grafana:
    build: 'config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
            - grafana

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

volumes:
  prometheus-data:
    driver: local

networks:
  network:
    driver: bridge
  monitoring:
    driver: bridge