version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "2181:2181"
    env_file:
      - kafka.env
    networks:
      - network
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo stat | nc localhost 2181" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - network
      - monitoring
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=kafka:9092"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - monitoring
      - network
    restart: unless-stopped

  postgres:
    image: 'postgres:15'
    container_name: 'bench_db'
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - network
      - monitoring
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bench-db -h localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@postgres:5432/bench-db?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring
    depends_on:
      - postgres

  grafana:
    build: 'config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
            - grafana

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - influxdb

  chronograf:
    image: chronograf:1.10
    container_name: chronograf
    ports:
      - "8888:8888"
    networks:
      - monitoring
    depends_on:
      - influxdb

  app:
    build: .
    container_name: 'app'
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - app.env
    networks:
      - network
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  prometheus-data:
    driver: local
  grafana-data:

networks:
  network:
    driver: bridge
  monitoring:
    driver: bridge