spring:
  application:
    name: BellTestBench
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always


server:
  port: 8081
